/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in to the system
         * @description Authenticates user and sets HTTP-only cookies for tokens.
         *
         *     **Cookies set:**
         *     - `access_token` - JWT access token (HttpOnly, Secure, SameSite=Lax)
         *     - `refresh_token` - JWT refresh token (HttpOnly, Secure, SameSite=Strict, Path=/api/v1/auth)
         *     - `csrf_token` - CSRF token for subsequent requests (readable by JavaScript)
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh tokens
         * @description Refreshes authentication tokens using the refresh_token cookie.
         *     New tokens are set via Set-Cookie headers.
         *
         *     **For cookie-based auth:** No request body needed, refresh_token is read from cookie.
         *     **For API clients:** Can pass refresh_token in request body.
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out from the system
         * @description Invalidates the refresh token and clears all authentication cookies.
         *
         *     **For cookie-based auth:** No request body needed, refresh_token is read from cookie.
         *     **For API clients:** Can pass refresh_token in request body.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List services
         * @description Public endpoint, no authentication required
         */
        get: operations["listServices"];
        put?: never;
        /** Create a service */
        post: operations["createService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a service by slug */
        get: operations["getService"];
        put?: never;
        post?: never;
        /**
         * Archive a service (soft delete)
         * @description Archives the service. Returns 409 if service has active events.
         */
        delete: operations["deleteService"];
        options?: never;
        head?: never;
        /** Update a service */
        patch: operations["updateService"];
        trace?: never;
    };
    "/api/v1/services/{slug}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an archived service */
        post: operations["restoreService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{slug}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get service tags */
        get: operations["getServiceTags"];
        /** Update service tags */
        put: operations["updateServiceTags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List groups */
        get: operations["listGroups"];
        put?: never;
        /** Create a group */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a group by slug */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        /**
         * Archive a group (soft delete)
         * @description Archives the group. Returns 409 if group has services with active events.
         */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        /** Update a group */
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/api/v1/groups/{slug}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an archived group */
        post: operations["restoreGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events */
        get: operations["listEvents"];
        put?: never;
        /**
         * Create an event
         * @description Creates an incident or maintenance. Groups in group_ids are expanded to services.
         */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an event */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        /**
         * Delete an event
         * @description Requires admin role
         */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List event updates */
        get: operations["listEventUpdates"];
        put?: never;
        /**
         * Add an update to an event
         * @description Also updates the event status
         */
        post: operations["addEventUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add services to an event
         * @description Adds services and/or groups. Groups are expanded to services.
         */
        post: operations["addServicesToEvent"];
        /**
         * Remove services from an event
         * @description Removes services only, not group associations.
         */
        delete: operations["removeServicesFromEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get event service change history
         * @description Returns chronological list of all service/group additions and removals.
         */
        get: operations["getEventServiceChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List templates */
        get: operations["listTemplates"];
        put?: never;
        /**
         * Create a template
         * @description Requires admin role
         */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a template */
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{slug}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview a template */
        post: operations["previewTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a template */
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My notification channels */
        get: operations["listMyChannels"];
        put?: never;
        /** Add a notification channel */
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a channel */
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        /** Update a channel */
        patch: operations["updateChannel"];
        trace?: never;
    };
    "/api/v1/me/channels/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a channel */
        post: operations["verifyChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My subscription */
        get: operations["getMySubscription"];
        put?: never;
        /** Create or update a subscription */
        post: operations["updateSubscription"];
        /** Delete a subscription */
        delete: operations["deleteSubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current public status */
        get: operations["getPublicStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event history */
        get: operations["getStatusHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ServiceStatus: "operational" | "degraded" | "partial_outage" | "major_outage" | "maintenance";
        /** @enum {string} */
        EventType: "incident" | "maintenance";
        /** @enum {string} */
        EventStatus: "investigating" | "identified" | "monitoring" | "resolved" | "scheduled" | "in_progress" | "completed";
        /** @enum {string} */
        Severity: "minor" | "major" | "critical";
        /** @enum {string} */
        ChangeAction: "added" | "removed";
        /** @enum {string} */
        ChannelType: "email" | "telegram";
        /** @enum {string} */
        Role: "user" | "operator" | "admin";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Service: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string;
            status: components["schemas"]["ServiceStatus"];
            group_ids: string[];
            order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            archived_at?: string | null;
        };
        ServiceGroup: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string;
            order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            archived_at?: string | null;
        };
        Event: {
            /** Format: uuid */
            id: string;
            title: string;
            type: components["schemas"]["EventType"];
            status: components["schemas"]["EventStatus"];
            severity?: components["schemas"]["Severity"] | null;
            description: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            resolved_at?: string | null;
            /** Format: date-time */
            scheduled_start_at?: string | null;
            /** Format: date-time */
            scheduled_end_at?: string | null;
            notify_subscribers: boolean;
            /** Format: uuid */
            template_id?: string | null;
            /** Format: uuid */
            created_by: string;
            service_ids?: string[] | null;
            group_ids?: string[] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        EventUpdate: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            event_id: string;
            status: components["schemas"]["EventStatus"];
            message: string;
            notify_subscribers: boolean;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        EventServiceChange: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            event_id: string;
            action: components["schemas"]["ChangeAction"];
            /** Format: uuid */
            service_id?: string | null;
            /** Format: uuid */
            group_id?: string | null;
            reason?: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        EventTemplate: {
            /** Format: uuid */
            id: string;
            slug: string;
            type: components["schemas"]["EventType"];
            title_template: string;
            body_template: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        NotificationChannel: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            type: components["schemas"]["ChannelType"];
            target: string;
            is_enabled: boolean;
            is_verified: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Subscription: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            service_ids: string[];
            /** Format: date-time */
            created_at: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            expires_in: number;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            first_name?: string;
            last_name?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        CreateServiceRequest: {
            name: string;
            slug: string;
            description?: string;
            status?: components["schemas"]["ServiceStatus"];
            group_ids?: string[];
            /** @default 0 */
            order: number;
            tags?: {
                [key: string]: string;
            };
        };
        UpdateServiceRequest: {
            name: string;
            slug: string;
            description?: string;
            status: components["schemas"]["ServiceStatus"];
            group_ids?: string[];
            order?: number;
        };
        UpdateTagsRequest: {
            tags: {
                [key: string]: string;
            };
        };
        CreateGroupRequest: {
            name: string;
            slug: string;
            description?: string;
            /** @default 0 */
            order: number;
        };
        UpdateGroupRequest: {
            name: string;
            slug: string;
            description?: string;
            order?: number;
        };
        CreateEventRequest: {
            title: string;
            type: components["schemas"]["EventType"];
            status: components["schemas"]["EventStatus"];
            severity?: components["schemas"]["Severity"];
            description: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            scheduled_start_at?: string;
            /** Format: date-time */
            scheduled_end_at?: string;
            /** @default false */
            notify_subscribers: boolean;
            /** Format: uuid */
            template_id?: string;
            service_ids?: string[];
            group_ids?: string[];
        };
        AddServicesRequest: {
            service_ids?: string[];
            group_ids?: string[];
            reason?: string;
        };
        RemoveServicesRequest: {
            service_ids: string[];
            reason?: string;
        };
        AddEventUpdateRequest: {
            status: components["schemas"]["EventStatus"];
            message: string;
            /** @default false */
            notify_subscribers: boolean;
        };
        CreateTemplateRequest: {
            slug: string;
            type: components["schemas"]["EventType"];
            title_template: string;
            body_template: string;
        };
        PreviewTemplateRequest: {
            service_name?: string;
            service_group_name?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            resolved_at?: string;
            /** Format: date-time */
            scheduled_start?: string;
            /** Format: date-time */
            scheduled_end?: string;
        };
        CreateChannelRequest: {
            type: components["schemas"]["ChannelType"];
            target: string;
        };
        UpdateChannelRequest: {
            is_enabled: boolean;
        };
        UpdateSubscriptionRequest: {
            service_ids?: string[];
        };
        UserResponse: {
            data?: components["schemas"]["User"];
        };
        LoginResponse: {
            data?: {
                user?: components["schemas"]["User"];
            };
        };
        ServiceResponse: {
            data?: components["schemas"]["Service"];
        };
        ServicesResponse: {
            data?: components["schemas"]["Service"][];
        };
        GroupResponse: {
            data?: components["schemas"]["ServiceGroup"];
        };
        GroupsResponse: {
            data?: components["schemas"]["ServiceGroup"][];
        };
        EventResponse: {
            data?: components["schemas"]["Event"];
        };
        EventsResponse: {
            data?: components["schemas"]["Event"][];
        };
        EventUpdateResponse: {
            data?: components["schemas"]["EventUpdate"];
        };
        EventUpdatesResponse: {
            data?: components["schemas"]["EventUpdate"][];
        };
        EventServiceChangesResponse: {
            data?: components["schemas"]["EventServiceChange"][];
        };
        TemplateResponse: {
            data?: components["schemas"]["EventTemplate"];
        };
        TemplatesResponse: {
            data?: components["schemas"]["EventTemplate"][];
        };
        PreviewTemplateResponse: {
            data?: {
                title?: string;
                body?: string;
            };
        };
        ChannelResponse: {
            data?: components["schemas"]["NotificationChannel"];
        };
        ChannelsResponse: {
            data?: components["schemas"]["NotificationChannel"][];
        };
        SubscriptionResponse: {
            data?: components["schemas"]["Subscription"];
        };
        TagsResponse: {
            data?: {
                tags?: {
                    [key: string]: string;
                };
            };
        };
        PublicStatusResponse: {
            data?: {
                events?: components["schemas"]["Event"][];
            };
        };
    };
    responses: {
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: {
                        message?: string;
                        /** @description Validation error details. Array of field errors or error string. */
                        details?: {
                            field: string;
                            message: string;
                        }[] | string;
                    };
                };
            };
        };
        /** @description Authentication required */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: {
                        message?: string;
                    };
                };
            };
        };
        /** @description Insufficient permissions */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: {
                        message?: string;
                    };
                };
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: {
                        message?: string;
                    };
                };
            };
        };
        /** @description Conflict */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: {
                        message?: string;
                    };
                };
            };
        };
    };
    parameters: {
        ServiceSlug: string;
        GroupSlug: string;
        EventId: string;
        TemplateSlug: string;
        ChannelId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["ConflictError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful. Tokens are set via Set-Cookie headers. */
            200: {
                headers: {
                    /** @description Authentication cookies (access_token, refresh_token, csrf_token) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Tokens refreshed. New tokens are set via Set-Cookie headers. */
            204: {
                headers: {
                    /** @description New authentication cookies */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Logout successful. Cookies are cleared via Set-Cookie headers. */
            204: {
                headers: {
                    /** @description Cleared authentication cookies (Max-Age=0) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    listServices: {
        parameters: {
            query?: {
                /** @description Filter by group membership */
                group_id?: string;
                status?: components["schemas"]["ServiceStatus"];
                /** @description Include archived services in the response */
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of services */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesResponse"];
                };
            };
        };
    };
    createService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceRequest"];
            };
        };
        responses: {
            /** @description Service created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            409: components["responses"]["ConflictError"];
        };
    };
    getService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["ServiceSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    deleteService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["ServiceSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
        };
    };
    updateService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["ServiceSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceRequest"];
            };
        };
        responses: {
            /** @description Service updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    restoreService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["ServiceSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
        };
    };
    getServiceTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["ServiceSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    updateServiceTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["ServiceSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagsRequest"];
            };
        };
        responses: {
            /** @description Tags updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    listGroups: {
        parameters: {
            query?: {
                /** @description Include archived groups in the response */
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupsResponse"];
                };
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            409: components["responses"]["ConflictError"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["GroupSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["GroupSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["GroupSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description Group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    restoreGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["GroupSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                type?: components["schemas"]["EventType"];
                status?: components["schemas"]["EventStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description Event created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    listEventUpdates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of updates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventUpdatesResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    addEventUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddEventUpdateRequest"];
            };
        };
        responses: {
            /** @description Update added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventUpdateResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    addServicesToEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddServicesRequest"];
            };
        };
        responses: {
            /** @description Services added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    removeServicesFromEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveServicesRequest"];
            };
        };
        responses: {
            /** @description Services removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getEventServiceChanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Change history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventServiceChangesResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplatesResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Template created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["TemplateSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    previewTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["TemplateSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewTemplateRequest"];
            };
        };
        responses: {
            /** @description Rendering result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewTemplateResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    listMyChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of channels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelsResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChannelRequest"];
            };
        };
        responses: {
            /** @description Channel created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChannelRequest"];
            };
        };
        responses: {
            /** @description Channel updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    verifyChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getMySubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    updateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    deleteSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getPublicStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current system status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStatusResponse"];
                };
            };
        };
    };
    getStatusHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStatusResponse"];
                };
            };
        };
    };
}
